# -*- coding: utf-8 -*-
#from . import sale_template_product_inherit
from . import stock_picking_inherit
from . import sale_order_inherit
from . import stock_move_inherit
from . import stock_rule_inherit
from . import stock_landed_cost_inherit
from . import stock_valuation_ajustement
from . import purchace_order_inherit
from . import account_invoice_inherit
from . import stock_picking_type_inherit
from . import account_payment_term_inherit
from . import res_partner
from . import asset_localization
from . import account_asset_asset_inherit
from . import payment_term
from . import account_move_line_inherit
from . import account_payment_inherit
from . import warehouse_inherit
from . import product_template_inherit
from . import id_type
from . import account_partner_ledger_inherit
from . import account_withhold_payment
from . import sale_channel_partner
from . import hr_payslip_run
